USE [master]
GO

/****** Object:  Database [tdin_server]    Script Date: 05/13/2012 16:49:56 ******/
CREATE DATABASE [tdin_server] ON  PRIMARY 
( NAME = N'tdin_server', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\tdin_server.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tdin_server_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\tdin_server_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tdin_server] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tdin_server].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tdin_server] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tdin_server] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tdin_server] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tdin_server] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tdin_server] SET ARITHABORT OFF 
GO

ALTER DATABASE [tdin_server] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [tdin_server] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [tdin_server] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tdin_server] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tdin_server] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tdin_server] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tdin_server] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tdin_server] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tdin_server] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tdin_server] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tdin_server] SET  ENABLE_BROKER 
GO

ALTER DATABASE [tdin_server] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tdin_server] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tdin_server] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tdin_server] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tdin_server] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tdin_server] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tdin_server] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tdin_server] SET  READ_WRITE 
GO

ALTER DATABASE [tdin_server] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tdin_server] SET  MULTI_USER 
GO

ALTER DATABASE [tdin_server] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tdin_server] SET DB_CHAINING OFF 
GO

