//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.5448
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerOpsHttp")]
public interface IServerOpsHttp
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerOpsHttp/GetClients", ReplyAction="http://tempuri.org/IServerOpsHttp/GetClientsResponse")]
    string GetClients();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServerOpsHttpChannel : IServerOpsHttp, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServerOpsHttpClient : System.ServiceModel.ClientBase<IServerOpsHttp>, IServerOpsHttp
{
    
    public ServerOpsHttpClient()
    {
    }
    
    public ServerOpsHttpClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerOpsHttpClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerOpsHttpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerOpsHttpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetClients()
    {
        return base.Channel.GetClients();
    }
}
